name: todo
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter_screenutil: ^5.9.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  date_picker_timeline: ^1.2.6
  flutter_slidable: ^3.1.0
  shared_preferences: ^2.2.3
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
